#!/bin/sh

dlls=(Pyro.AppCommon.dll         Pyro.Executor.dll        Pyro.PiLang.dll
Pyro.Core.dll              Pyro.LanguageCommon.dll  Pyro.RhoLang.dll
Pyro.ExecutionContext.dll  Pyro.Network.dll)

src="/$WORK_LETTER/Packages/Pyro/Bin"

for dll in "${dlls[@]}";
do
	echo $dll
	cp $src/$dll .
done

