#!/bin/sh

src='/s/Packages/Pyro/Bin'

dlls=(Pyro.AppCommon.dll Pyro.Core.dll Pyro.ExecutionContext.dll Pyro.Executor.dll Pyro.LanguageCommon.dll Pyro.PiLang.dll Pyro.RhoLang.dll)

for dll in ${dlls[@]}
do
    echo $dll
    cp $src/$dll .
done

